### ISSUE TITLE
ModuleNotFoundError: No module named 'bs4'

### ISSUE THREAD

**Issue by gniuskap** [bder222/NBA-scoreboard#3]
Hi bderr222!

So I was able to get the teams showing as well as the time they play, but for some reason, the spreads are not showing up. After I enter both scripts below under the Usage section I get the following:

>  sudo python3 /home/pi/NBA-scoreboard/NBA_Data.py
> 
>  sudo python3 /home/pi/NBA-scoreboard/Spreads_New_Day.py
> 

ModuleNotFoundError: No module named 'bs4'

Thanks for taking the time to help me out, I really appreciate it!

**Comment by bder222** [comment]
Looks like I forgot another dependency! The following command in terminal should install bs4 (AKA BeautifulSoup):

>sudo pip install bs4

I’ll add this to the install script as well. Thanks for helping me find the bugs!

**Comment by gniuskap** [comment]
My pleasure, thanks for the responses!

I tried to run that script but I got a prompt saying

    sudo: pip: command not found

I think I might be missing a step. I am going to attempt a fresh install tomorrow morning to see if that fixes things.

Thanks again!

**Comment by bder222** [comment]
I think you’ll want to try installing the pip command using:

```
sudo apt-get update 
sudo apt-get install python3-pip
```

This should install the pip library for python, python 3 specifically. If you still get the error for not finding the bs4 library or pip command not found, try using 

`sudo pip3 install bs4`

Pip3 will install bs4 specifically for python 3, whereas pip will try to use your default version of python, which can sometimes be python 2. 

Hopefully this helps!

**Comment by bder222** [comment]
I also just updated the install script and readme with the above recommendations and tested them, so a fresh install may make things a little easier!

**Comment by gniuskap** [comment]
This worked thank you!

**Comment by gniuskap** [comment]
Hey Bder222, thanks so much man. You were an awesome help!!!

Everything seems to work, but only the spreads and upcoming games arent showing up. I will try to mess around with it. I feel like it is the crontab, updating at 11 AM (It is past that time here). I am hoping that maybe it will populate tomorrow morning.

I just have a quick question. Is there any way to have it static on just one team?

Thanks again!!

**Comment by gniuskap** [comment]
Sorted it out! Thanks a bunch. If you do have a simple solution for just 1 team, please let me know. You rock!
