### ISSUE TITLE
Time zone will be cut off  when there are 4 digits in the clock

### ISSUE THREAD

**Issue by gniuskap** [bder222/NBA-scoreboard#4]
Hello!

 I found that also some games do not include the Timezone. I think it might be easiest to get rid of this on the screen if possible.

I attached some images
![IMG_1167](https://user-images.githubusercontent.com/80427853/110974571-aa116b00-832c-11eb-99bb-6fce821893ab.jpg)
![IMG_1165](https://user-images.githubusercontent.com/80427853/110974576-aaaa0180-832c-11eb-8e75-5941b9879862.jpg)
![IMG_1166](https://user-images.githubusercontent.com/80427853/110974582-abdb2e80-832c-11eb-9b22-61aae48ab348.jpg)

Thanks!

**Comment by bder222** [comment]
Ah it used to get rid of the time zone but I noticed some games have the time zone included after the All-star break. This should be easy to fix, it looks like the data source added a bunch of spaces after the time zone which is what changed the time displayed on the board. I'll update this issue once I get a chance to test the solution.

**Comment by bder222** [comment]
I think this is issue has been fixed. There are no time zones displayed for upcoming games. Let me know if this works for you!

**Comment by bder222** [comment]
Time zones are no longer displayed. Changed gameStatus string to search for "ET" and ignore everything after.
