### ISSUE TITLE
cannot get past FileNotFoundError /home/pi/NBA-scoreboard/NBASpreads.json

### ISSUE THREAD

**Issue by machinasdei** [bder222/NBA-scoreboard#5]
it appears that this file never gets created and its continuously looking for it.  Do you have the file NBASpreads.json that you can post/share?  I dont know why this isn't being found or created by your scripts?

10/20/2021 23:18 - NBA Data Gathered
Traceback (most recent call last):
  File "/home/scott/NBA-scoreboard/NBA_Data.py", line 58, in <module>
    NBA_Data().JSON_dump()
  File "/home/scott/NBA-scoreboard/NBA_Data.py", line 51, in JSON_dump
    NBA_Spreads().Spreads_Update()
  File "/home/scott/NBA-scoreboard/NBA_Spreads.py", line 43, in Spreads_Update
    with open(self.path, 'r') as file:
FileNotFoundError: [Errno 2] No such file or directory: '/home/pi/NBA-scoreboard/NBASpreads.json'

**Comment by machinasdei** [comment]
thanks for the file.
I can get it to run sorta, but it wont render now....simply outputs this;
10/21/2021 22:36 - NBA Data Gathered
10/21/2021 22:36 - Live game.
10/21/2021 22:38 - NBA Data Gathered
10/21/2021 22:38 - Live game.
10/21/2021 22:40 - NBA Data Gathered
10/21/2021 22:40 - Live game.

-repeat 
but nothing on the LED - any ideas?

**Comment by bder222** [comment]
I realized that today as well, Bovada changed the formatting of their API so the indexing is incorrect when I pull spreads. I’ll have to modify that portion of the code to get it to work.
