### ISSUE TITLE
Error loading NBA_Render.py

### ISSUE THREAD

**Issue by ddman2** [bder222/NBA-scoreboard#7]
I received an error initially because the NBA_Render.py script points to /home/pi/" to look for the fonts as opposed to looking within the NBA-scoreboard directory...  I was able to correct by replacing /home/pi/ with self.path +

`self.font.LoadFont("/home/pi/rpi-rgb-led-matrix/fonts/6x12.bdf")` changed to `self.font.LoadFont(self.path + "rpi-rgb-led-matrix/fonts/6x12.bdf")`
...
`self.font2.LoadFont("/home/pi/rpi-rgb-led-matrix/fonts/4x6.bdf")` changed to `self.font2.LoadFont(self.path + "rpi-rgb-led-matrix/fonts/4x6.bdf")`

**Comment by bder222** [comment]
Interesting, did you have any issues when running the install.sh script? That should download the rpi-rgb-led-matrix library to the home/pi directory and not into the NBA-scoreboard directory. If it was downloaded into the NBA-scoreboard directory, it should throw an exception when running install.sh in line 9:

`cd /home/pi/rpi-rgb-led-matrix`

**Comment by ddman2** [comment]
No issue of which I'm aware. I will double check, but I believe it installed the RGB-matrix files into the NBA-scoreboard directory.

**Comment by bder222** [comment]
I think I see where my error was in the install script. I used `cd` with no operand and should probably use `cd ~` instead to change the working directory to /home. This has been corrected in the install script.
