### ISSUE TITLE
unable to pull time zone from dateutil

### ISSUE THREAD

**Issue by Coop21** [bder222/NBA-scoreboard#9]
I just updated to the latest version of the program.  When I try to run the program now I get the following message.

![image](https://user-images.githubusercontent.com/80079281/162601579-81da9ca2-de95-40df-ba07-df3ed034d490.png)

I looked up dateutil and installed it, but I don't have any idea how it's supposed to work.

**Comment by bder222** [comment]
You'll have to use sudo when installing the dateutil library since the rendering requires sudo permissions. Try this in a command window:

`sudo pip3 install python-dateutil`

I'll add this to the install.sh script so that this is automatically done on a new install.

**Comment by Coop21** [comment]
I probably should have figured that out on my own.  Didn't even think of using the sudo command.  Everything is working now.  Appreciate the answer!

**Comment by bder222** [comment]
No problem, I forgot to put it in the main install script so thanks for finding it.
